### ISSUE TITLE
Resolve security hole with requests <= 2.19.1

### ISSUE THREAD

**Issue by jrbattles** [fire-ants/mlb-machine-learning#10]
Known moderate severity security vulnerability detected in requests <= 2.19.1defined in requirements.txt.requirements.txt update suggested: requests ~> 2.20.0. | Known moderate severity security vulnerability detected in requests <= 2.19.1defined in requirements.txt. | requirements.txt update suggested: requests ~> 2.20.0.
Known moderate severity security vulnerability detected in requests <= 2.19.1defined in requirements.txt.
requirements.txt update suggested: requests ~> 2.20.0.

**Comment by goyetc** [comment]
Resolved.. updated to 2.20.0 in requirements.txt
