### ISSUE TITLE
Clean up pipeline and add task

### ISSUE THREAD

**Issue by kennysabarese** [fire-ants/mlb-machine-learning#14]
Pipeline should be in directory "ci" 
change to pipeline.yml
add task execute_machine_learning to pipeline.yml

**Comment by goyetc** [comment]
What pipeline? Not clear if you're talking about microservice pipeline or 'holistic' pipeline that spans microservices

**Comment by kennysabarese** [comment]
this issue is referring to the machine learning micro service pipeline. (the "holistic" pipeline is called dataflow and has it's own repo)
